/* tslint:disable */
/* eslint-disable */
/**
 * vol
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExecPost200Response
 */
export interface ExecPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ExecPost200Response
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof ExecPost200Response
     */
    err: string;
}

/**
 * Check if a given object implements the ExecPost200Response interface.
 */
export function instanceOfExecPost200Response(value: object): value is ExecPost200Response {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('err' in value) || value['err'] === undefined) return false;
    return true;
}

export function ExecPost200ResponseFromJSON(json: any): ExecPost200Response {
    return ExecPost200ResponseFromJSONTyped(json, false);
}

export function ExecPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'err': json['err'],
    };
}

export function ExecPost200ResponseToJSON(value?: ExecPost200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'err': value['err'],
    };
}

