/* tslint:disable */
/* eslint-disable */
/**
 * vol
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExecPost200Response
 */
export interface ExecPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ExecPost200Response
     */
    output: string;
    /**
     * 
     * @type {string}
     * @memberof ExecPost200Response
     */
    error: string;
}

/**
 * Check if a given object implements the ExecPost200Response interface.
 */
export function instanceOfExecPost200Response(value: object): value is ExecPost200Response {
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ExecPost200ResponseFromJSON(json: any): ExecPost200Response {
    return ExecPost200ResponseFromJSONTyped(json, false);
}

export function ExecPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'output': json['output'],
        'error': json['error'],
    };
}

export function ExecPost200ResponseToJSON(value?: ExecPost200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'output': value['output'],
        'error': value['error'],
    };
}

