/* tslint:disable */
/* eslint-disable */
/**
 * vol
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface K8sCommandPostRequest
 */
export interface K8sCommandPostRequest {
    /**
     * 
     * @type {string}
     * @memberof K8sCommandPostRequest
     */
    action: string;
    /**
     * 
     * @type {string}
     * @memberof K8sCommandPostRequest
     */
    resource: string;
    /**
     * 
     * @type {string}
     * @memberof K8sCommandPostRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof K8sCommandPostRequest
     */
    namespace: string;
}

/**
 * Check if a given object implements the K8sCommandPostRequest interface.
 */
export function instanceOfK8sCommandPostRequest(value: object): value is K8sCommandPostRequest {
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('resource' in value) || value['resource'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('namespace' in value) || value['namespace'] === undefined) return false;
    return true;
}

export function K8sCommandPostRequestFromJSON(json: any): K8sCommandPostRequest {
    return K8sCommandPostRequestFromJSONTyped(json, false);
}

export function K8sCommandPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): K8sCommandPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'],
        'resource': json['resource'],
        'name': json['name'],
        'namespace': json['namespace'],
    };
}

export function K8sCommandPostRequestToJSON(value?: K8sCommandPostRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'action': value['action'],
        'resource': value['resource'],
        'name': value['name'],
        'namespace': value['namespace'],
    };
}

