/* tslint:disable */
/* eslint-disable */
/**
 * vol
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface K8sLogGet200Response
 */
export interface K8sLogGet200Response {
    /**
     * 
     * @type {string}
     * @memberof K8sLogGet200Response
     */
    error: string;
    /**
     * 
     * @type {string}
     * @memberof K8sLogGet200Response
     */
    output: string;
}

/**
 * Check if a given object implements the K8sLogGet200Response interface.
 */
export function instanceOfK8sLogGet200Response(value: object): value is K8sLogGet200Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    return true;
}

export function K8sLogGet200ResponseFromJSON(json: any): K8sLogGet200Response {
    return K8sLogGet200ResponseFromJSONTyped(json, false);
}

export function K8sLogGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): K8sLogGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
        'output': json['output'],
    };
}

export function K8sLogGet200ResponseToJSON(value?: K8sLogGet200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'error': value['error'],
        'output': value['output'],
    };
}

