/* tslint:disable */
/* eslint-disable */
/**
 * vol
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface YamlPostRequest
 */
export interface YamlPostRequest {
    /**
     * 
     * @type {string}
     * @memberof YamlPostRequest
     */
    filename: string;
    /**
     * 
     * @type {string}
     * @memberof YamlPostRequest
     */
    content: string;
}

/**
 * Check if a given object implements the YamlPostRequest interface.
 */
export function instanceOfYamlPostRequest(value: object): value is YamlPostRequest {
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function YamlPostRequestFromJSON(json: any): YamlPostRequest {
    return YamlPostRequestFromJSONTyped(json, false);
}

export function YamlPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): YamlPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'filename': json['filename'],
        'content': json['content'],
    };
}

export function YamlPostRequestToJSON(value?: YamlPostRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'filename': value['filename'],
        'content': value['content'],
    };
}

