import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "VOL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark w-full h-screen">
        <div className="flex">
          <div className="w-1/12 border-r border-gray-200 min-w-max">
            <Navbar />
          </div>
          <div className="grow">{children}</div>
        </div>
      </body>
    </html>
  );
}
