import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "VOL",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          http-equiv="Content-Security-Policy"
          content="default-src https: http: 'self'; script-src https: http: 'unsafe-inline';"
        />
      </head>
      <body className="dark w-full h-screen">
        <div className="flex">
          <div className="w-1/12 border-r border-gray-200">
            <Navbar />
          </div>
          <div className="w-11/12">{children}</div>
        </div>
      </body>
    </html>
  );
}
