# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Check Next.js

on:
  pull_request:
    branches: ["master"]

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('bun.lockb') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('bun.lockb') }}

      - name: Install dependencies
        run: bun install

      - name: Lint with Next.js
        run: bun run lint
